[package]
name = "minecraft-flipbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
once_cell = "1.17.0"
serde_json = "1.0"
